# Generated by Django 3.0 on 2019-12-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inflow_funds', models.CharField(max_length=20)),
                ('outflow_funds', models.CharField(max_length=20)),
                ('investor_id', models.CharField(max_length=20)),
                ('originator_id', models.CharField(max_length=20)),
                ('item_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('investor_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('disposable_funds', models.CharField(max_length=20)),
                ('expenditure', models.CharField(default='0', max_length=20)),
                ('recharge', models.CharField(default='0', max_length=20)),
                ('state', models.CharField(choices=[('one', '未认证'), ('two', '认证成功')], max_length=10)),
                ('item_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('short_title', models.CharField(max_length=30)),
                ('ind_id', models.CharField(choices=[('one', '移动互联'), ('two', '节能环保'), ('three', '文化传媒'), ('four', '新能源'), ('five', '消费服务'), ('six', '其他')], max_length=10)),
                ('country', models.CharField(choices=[('one', '北京'), ('two', '天津'), ('three', '浙江'), ('four', '上海'), ('five', '福建'), ('six', '湖北'), ('seven', '其他')], max_length=10)),
                ('phase', models.CharField(choices=[('one', '种子期'), ('two', '成长期'), ('three', '扩张期'), ('four', '成熟期')], max_length=10)),
                ('amount', models.CharField(max_length=40)),
                ('transfer_ratio', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=40)),
                ('link_url', models.CharField(max_length=11)),
                ('raised_funds', models.CharField(max_length=20)),
                ('originator_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Originator',
            fields=[
                ('originator_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('item_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('userPwd', models.CharField(max_length=20)),
                ('real_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('avatar', models.CharField(max_length=128)),
            ],
        ),
    ]
