# Generated by Django 3.0 on 2019-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='investor_id',
            new_name='raised_funds',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='item_id',
            new_name='remaining_data',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='originator_id',
            new_name='support_num',
        ),
        migrations.AlterField(
            model_name='investor',
            name='state',
            field=models.CharField(choices=[('one', '认证成功'), ('two', '未认证')], max_length=10),
        ),
    ]
